### ISSUE TITLE
Read from configuration file

### ISSUE THREAD

**Issue by arsham** [arsham/expvastic#13]
Possible configuration syntax:

```yml
conf:
    debug_evel: info

readers:
    my_app: # service name
        type: json
        location: localhost:1234/debug/vars
        cert_location: /path/to/certs
        timeout: 10s
        interval: 10s
        map_file: maps/my_app.map # to map the names etc. for name conversion
    nginx:
        type: logfile
        location: /var/log/nginx.log
        timeout: 20s
        interval: 3s
    systemd:
        type: syslog
        timeout: 20s
        interval: 5m

recorders:
    elastic1: # service name
        type: elasticsearch
        location: 127.0.0.1:9200
        index_name:
            name: expvastic
            dated: true
            date_by: 1d # one day, or 1h for one hour
        type_name:
            app_name # default, which will be elastic1
    file1:
        type: file # to record to a file
        location: /var/log/my_app/data.json
        format: json # or nginx log format
        rotate: 100mb # to rotate the file like logrotate

routes:
    route1:
        readers:
            - my_app
            - self # refers to expvastic application
        recorders:
            - elastic1
    route2:
        readers:
            - my_app
        recorders:
            - elastic1
            - file1
    route3:
        readers:
            - nginx
            - systemd
        recorders:
            - elastic1
            - file1
```
