### ISSUE TITLE
Docker container discovery

### ISSUE THREAD

**Issue by arsham** [arsham/expvastic#14]
Query docker for the containers by their tags. Possible configuration:

```yaml
settings:
    cluster-store: consul://192.168.1.1:8500

reader: # or recorder
    type: expvar
    endpoint: 
         service: docker
         url: my_app:1234/debug/vars
```
